const beerAustria = [
    {name: 'Gösser', brewery: 'Gösser Brauerei', country: 'Austria', continent: 'Europe', image: 'img/Austria/Gosser/Gosser_1.png'},
    {name: 'Gösser', brewery: 'Gösser Brauerei', country: 'Austria', continent: 'Europe', image: 'img/Austria/Gosser/Gosser_2.png'},
    {name: 'Gösser </br> Natur Radler', brewery: 'Gösser Brauerei', country: 'Austria', continent: 'Europe', image: 'img/Austria/Gosser/Gosser_Natur_Radler.png'},
    {name: 'Stiegl', brewery: 'Stieglbrauerei zu Salzburg', country: 'Austria', continent: 'Europe', image: 'img/Austria/Stiegl/Stiegl.png'},
    {name: 'Zipfer', brewery: 'Brauerei Zipf', country: 'Austria', continent: 'Europe', image: 'img/Austria/Zipfer/Zipfer.png'},
    {name: 'Zipfer </br> Urtyp', brewery: 'Brauerei Zipf', country: 'Austria', continent: 'Europe', image: 'img/Austria/Zipfer/Zipfer_Urtyp.png'},
    {name: 'Edelweiss </br> Hefetrüb', brewery: 'Hofbräu Kaltenhausen', country: 'Austria', continent: 'Europe', image: 'img/Austria/Edelweiss/Edelweiss_Hefetrub.png'},
    {name: 'Edelweiss </br> Dunkel', brewery: 'Hofbräu Kaltenhausen', country: 'Austria', continent: 'Europe', image: 'img/Austria/Edelweiss/Edelweiss_Dunkel.png'},
    {name: 'Kaiser </br> Fasstyp', brewery: 'Brau Union Österreich AG', country: 'Austria', continent: 'Europe', image: 'img/Austria/Kaiser/Kaiser.png'},
    {name: 'Innviertler </br> Hell', brewery: 'Brauerei Raschhofer', country: 'Austria', continent: 'Europe', image: 'img/Austria/Raschhofer/Innviertler_Hell.png'},
    {name: 'Wurmhöringer', brewery: 'Wurmhöringer', country: 'Austria', continent: 'Europe', image: 'img/Austria/Wurmhoringer/Wurmhoringer.png'},
    {name: 'Schützen', brewery: 'Brauerei Wieselburg', country: 'Austria', continent: 'Europe', image: 'img/Austria/Schutzen/Schutzen.png'},
    {name: 'Raschhofer', brewery: 'Brauerei Raschhofer', country: 'Austria', continent: 'Europe', image: 'img/Austria/Raschhofer/Raschhofer.png'},
    {name: 'Puntigamer', brewery: 'Brauerei Puntigam', country: 'Austria', continent: 'Europe', image: 'img/Austria/Puntigamer/Puntigamer.png'},
    {name: 'Rieder', brewery: 'Brauerei Ried', country: 'Austria', continent: 'Europe', image: 'img/Austria/Rieder/Rieder.png'},
];