const beerBelgium = [
    {name: 'Leffe Radieuse', brewery: 'Leffe', country: 'Belgium', continent: 'Europe', image: 'img/Belgium/Leffe/Leffe_Radieuse.png'},
    {name: 'Stella Artois', brewery: 'Stella Artois', country: 'Belgium', continent: 'Europe', image: 'img/Belgium/StellaArtois/Stella_Artois_1.png'},
    {name: 'Stella Artois', brewery: 'Stella Artois', country: 'Belgium', continent: 'Europe', image: 'img/Belgium/StellaArtois/Stella_Artois_2.png'},
    {
        name: 'Stella Artois',
        brewery: 'Stella Artois',
        country: 'Belgium',
        continent: 'Europe',
        image: 'img/Belgium/StellaArtois/Stella_Artois_3.png'
    },
    {name: 'Vieux Temps', brewery: 'Stella Artois', country: 'Belgium', continent: 'Europe', image: 'img/Belgium/StellaArtois/Vieux_Temps.png'},
    {name: 'Gulden Draak Classic', brewery: 'Gulden Draak', country: 'Belgium', continent: 'Europe', image: 'img/Belgium/GuldenDraak/Gulden_Draak_Classic.png'},
    {
        name: 'Gulden Draak 9000 Quadruple',
        brewery: 'Gulden Draak',
        country: 'Belgium',
        continent: 'Europe',
        image: 'img/Belgium/GuldenDraak/Gulden_Draak_9000.png'
    },
    {name: 'Heineken', brewery: 'Heineken', country: 'Belgium', continent: 'Europe', image: 'img/Belgium/Heineken/Heineken.png'},
    {name: 'Heineken Original', brewery: 'Heineken', country: 'Belgium', continent: 'Europe', image: 'img/Belgium/Heineken/Heineken_Original.png'},
    {name: 'Vedett Extra Ordinary IPA', brewery: 'Vedett', country: 'Belgium', continent: 'Europe', image: 'img/Belgium/Vedett/Vedett_IPA.png'},
    {name: 'Piraat', brewery: 'Piraat', country: 'Belgium', continent: 'Europe', image: 'img/Belgium/Piraat/Piraat.png'},
    {name: 'Piraat Triple Hop', brewery: 'Piraat', country: 'Belgium', continent: 'Europe', image: 'img/Belgium/Piraat/Piraat_Triple_Hop.png'},
    {name: 'Kwak', brewery: 'Kwak', country: 'Belgium', continent: 'Europe', image: 'img/Belgium/Kwak/Kwak.png'},
    {name: 'Belle Vue Kriek', brewery: 'Belle Vue', country: 'Belgium', continent: 'Europe', image: 'img/Belgium/BelleVue/Belle_Vue.png'},
    {name: 'Hélécine Brune', brewery: 'Abbay de Hélécine', country: 'Belgium', continent: 'Europe', image: 'img/Belgium/Helecine/Helecine_Brune.png'},
    {name: 'Ciney Blonde', brewery: 'Ciney', country: 'Belgium', continent: 'Europe', image: 'img/Belgium/Ciney/Ciney_Blonde.png'},
    {name: 'Liefmans Master Blenders', brewery: 'Liefmans', country: 'Belgium', continent: 'Europe', image: 'img/Belgium/Liefmans/Liefmans.png'},
    {name: 'Judas', brewery: 'Judas', country: 'Belgium', continent: 'Europe', image: 'img/Belgium/Judas/Judas.png'},
    {name: 'Affligem', brewery: 'Affligem Brouwerij', country: 'Belgium', continent: 'Europe', image: 'img/Belgium/Affligem/Affligem.png'},
    {name: 'Abbaye d\'Aulne', brewery: 'Abbaye d\'Aulne', country: 'Belgium', continent: 'Europe', image: 'img/Belgium/AbbayedAulne/Abbaye_dAulne.png'},
    {name: 'Chimay', brewery: 'Chimay', country: 'Belgium', continent: 'Europe', image: 'img/Belgium/Chimay/Chimay.png'},
    {name: 'Grimbergen Blonde', brewery: 'Grimbergen', country: 'Belgium', continent: 'Europe', image: 'img/Belgium/Grimbergen/Grimbergen_Blonde.png'},
    {name: 'Grimbergen Rouge', brewery: 'Grimbergen', country: 'Belgium', continent: 'Europe', image: 'img/Belgium/Grimbergen/Grimbergen_Rouge.png'},
    {name: 'Grimbergen Blanche', brewery: 'Grimbergen', country: 'Belgium', continent: 'Europe', image: 'img/Belgium/Grimbergen/Grimbergen_Blanche.png'},
    {name: 'Grimbergen Double', brewery: 'Grimbergen', country: 'Belgium', continent: 'Europe', image: 'img/Belgium/Grimbergen/Grimbergen_Double.png'},
    {name: 'Grimbergen Triple D\'Abbaye', brewery: 'Grimbergen', country: 'Belgium', continent: 'Europe', image: 'img/Belgium/Grimbergen/Grimbergen_Triple.png'},
    {name: 'Hoegaarden', brewery: 'Brouwerij Van Hoegaarden', country: 'Belgium', continent: 'Europe', image: 'img/Belgium/Hoegaarden/Hoegaarden.png'},
    {name: 'Hoegaarden Blanche Wit', brewery: 'Brouwerij Van Hoegaarden', country: 'Belgium', continent: 'Europe', image: 'img/Belgium/Hoegaarden/Hoegaarden_Blanche_Wit.png'},
    {name: 'Poperings Hommelbier', brewery: 'Poperings', country: 'Belgium', continent: 'Europe', image: 'img/Belgium/Poperings/Poperings_Hommelbier.png'},
    {name: 'Bornem Double', brewery: 'Bornem', country: 'Belgium', continent: 'Europe', image: 'img/Belgium/Bornem/Bornem_Double.png'},
    {name: 'Bornem Tripel', brewery: 'Bornem', country: 'Belgium', continent: 'Europe', image: 'img/Belgium/Bornem/Bornem_Tripel.png'},
];