const beerBelgium = [
    {name: 'Leffe Radieuse', brewery: 'Leffe', country: 'Belgium', continent: 'Europe', image: 'img/Belgium/28.png'},
    {name: 'Stella Artois', brewery: 'Stella Artois', country: 'Belgium', continent: 'Europe', image: 'img/Belgium/27.png'},
    {name: 'Stella Artois', brewery: 'Stella Artois', country: 'Belgium', continent: 'Europe', image: 'img/Belgium/26.png'},
    {
        name: 'Stella Artois',
        brewery: 'Stella Artois',
        country: 'Belgium',
        continent: 'Europe',
        image: 'img/Belgium/StellaArtois/Stella_Artois.png'
    },
    {name: 'Vieux Temps', brewery: 'Stella Artois', country: 'Belgium', continent: 'Europe', image: 'img/Belgium/16.png'},
    {name: 'Gulden Draak Classic', brewery: 'Brouwerij Van Steenberge', country: 'Belgium', continent: 'Europe', image: 'img/Belgium/25.png'},
    {
        name: 'Gulden Draak 9000 Quadruple',
        brewery: 'Brouwerij Van Steenberge',
        country: 'Belgium',
        continent: 'Europe',
        image: 'img/Belgium/24.png'
    },
    {name: 'Heineken', brewery: 'Heineken', country: 'Belgium', continent: 'Europe', image: 'img/Belgium/23.png'},
    {name: 'Vedett Extra Ordinary IPA', brewery: 'Vedett', country: 'Belgium', continent: 'Europe', image: 'img/Belgium/22.png'},
    {name: 'Piraat', brewery: 'Brouwerij Van Steenberge', country: 'Belgium', continent: 'Europe', image: 'img/Belgium/21.png'},
    {name: 'Piraat Triple Hop', brewery: 'Brouwerij Van Steenberge', country: 'Belgium', continent: 'Europe', image: 'img/Belgium/20.png'},
    {name: 'Kwak', brewery: 'Kwak', country: 'Belgium', continent: 'Europe', image: 'img/Belgium/19.png'},
    {name: 'Belle Vue Kriek', brewery: 'Belle Vue', country: 'Belgium', continent: 'Europe', image: 'img/Belgium/18.png'},
    {name: 'Hélécine Brune', brewery: 'Abbay de Hélécine', country: 'Belgium', continent: 'Europe', image: 'img/Belgium/17.png'},
    {name: 'Ciney Blonde', brewery: 'Brouwerij Alken-Maes', country: 'Belgium', continent: 'Europe', image: 'img/Belgium/15.png'},
    {name: 'Liefmans Master Blenders', brewery: 'Liefmans', country: 'Belgium', continent: 'Europe', image: 'img/Belgium/14.png'},
    {name: 'Judas', brewery: 'Brouwerijen Alken-Maes', country: 'Belgium', continent: 'Europe', image: 'img/Belgium/13.png'},
    {name: 'Affligem', brewery: 'Affligem Brouwerij', country: 'Belgium', continent: 'Europe', image: 'img/Belgium/12.png'},
    {name: 'Abbaye d\'Aulne', brewery: 'Abbaye d\'Aulne', country: 'Belgium', continent: 'Europe', image: 'img/Belgium/AbbayedAulne/Abbaye_dAulne.png'},
    {name: 'Chimay', brewery: 'Chimay', country: 'Belgium', continent: 'Europe', image: 'img/Belgium/10.png'},
    {name: 'Grimbergen Blonde', brewery: 'Grimbergen', country: 'Belgium', continent: 'Europe', image: 'img/Belgium/9.png'},
    {name: 'Grimbergen Rouge', brewery: 'Grimbergen', country: 'Belgium', continent: 'Europe', image: 'img/Belgium/8.png'},
    {name: 'Grimbergen Blanche', brewery: 'Grimbergen', country: 'Belgium', continent: 'Europe', image: 'img/Belgium/7.png'},
    {name: 'Grimbergen Double', brewery: 'Grimbergen', country: 'Belgium', continent: 'Europe', image: 'img/Belgium/Grimbergen/Grimbergen_Double.png'},
    {name: 'Grimbergen Triple D\'Abbaye', brewery: 'Grimbergen', country: 'Belgium', continent: 'Europe', image: 'img/Belgium/6.png'},
    {name: 'Hoegaarden', brewery: 'Brouwerij Van Hoegaarden', country: 'Belgium', continent: 'Europe', image: 'img/Belgium/5.png'},
    {name: 'Hoegaarden Blanche Wit', brewery: 'Brouwerij Van Hoegaarden', country: 'Belgium', continent: 'Europe', image: 'img/Belgium/4.png'},
    {name: 'Poperings Hommelbier', brewery: 'Brouwerij Van Eecke', country: 'Belgium', continent: 'Europe', image: 'img/Belgium/3.png'},
    {name: 'Bornem Double', brewery: 'Brouwerij Van Steenberge', country: 'Belgium', continent: 'Europe', image: 'img/Belgium/2.png'},
    {name: 'Bornem Tripel', brewery: 'Brouwerij Van Steenberge', country: 'Belgium', continent: 'Europe', image: 'img/Belgium/1.png'},
];