const beerBulgaria = [
    {name: 'Zagorka', brewery: 'Zagorka', country: 'Bulgaria', continent: 'Europe', image: 'img/Bulgaria/Zagorka/Zagorka_1.png'},
    {name: 'Zagorka', brewery: 'Zagorka', country: 'Bulgaria', continent: 'Europe', image: 'img/Bulgaria/Zagorka/Zagorka_2.png'},
    {name: 'Zagorka', brewery: 'Zagorka', country: 'Bulgaria', continent: 'Europe', image: 'img/Bulgaria/Zagorka/Zagorka_3.png'},
    {name: 'Zagorka </br> Special', brewery: 'Zagorka', country: 'Bulgaria', continent: 'Europe', image: 'img/Bulgaria/Zagorka/Zagorka_Special.png'},
    {name: 'Kamenitza', brewery: 'Kamenitza', country: 'Bulgaria', continent: 'Europe', image: 'img/Bulgaria/Kamenitza/Kamenitza_1.png'},
    {name: 'Kamenitza', brewery: 'Kamenitza', country: 'Bulgaria', continent: 'Europe', image: 'img/Bulgaria/Kamenitza/Kamenitza_2.png'},
    {name: 'Kamenitza', brewery: 'Kamenitza', country: 'Bulgaria', continent: 'Europe', image: 'img/Bulgaria/Kamenitza/Kamenitza_3.png'},
    {name: 'Kamenitza', brewery: 'Kamenitza', country: 'Bulgaria', continent: 'Europe', image: 'img/Bulgaria/Kamenitza/Kamenitza_4.png'},
    {name: 'Kamenitza', brewery: 'Kamenitza', country: 'Bulgaria', continent: 'Europe', image: 'img/Bulgaria/Kamenitza/Kamenitza_5.png'},
    {name: 'Kamenitza </br> Dark', brewery: 'Kamenitza', country: 'Bulgaria', continent: 'Europe', image: 'img/Bulgaria/Kamenitza/Kamenitza_Dark.png'},
    {name: 'Ariana', brewery: 'Ariana', country: 'Bulgaria', continent: 'Europe', image: 'img/Bulgaria/Ariana/Ariana_1.png'},
    {name: 'Ariana', brewery: 'Ariana', country: 'Bulgaria', continent: 'Europe', image: 'img/Bulgaria/Ariana/Ariana_2.png'},
    {name: 'Stolichno </br> Weiss', brewery: 'Stolichno', country: 'Bulgaria', continent: 'Europe', image: 'img/Bulgaria/Stolichno/Stolichno_Weiss.png'},
    {name: 'Stolichno </br> Bock', brewery: 'Stolichno', country: 'Bulgaria', continent: 'Europe', image: 'img/Bulgaria/Stolichno/Stolichno_Bock.png'},
    {name: 'Stolichno </br> Pale Bock', brewery: 'Stolichno', country: 'Bulgaria', continent: 'Europe', image: 'img/Bulgaria/Stolichno/Stolichno_Pale_Bock.png'},
    {name: 'Stolichno </br> Crafted Quality', brewery: 'Stolichno', country: 'Bulgaria', continent: 'Europe', image: 'img/Bulgaria/Stolichno/Stolichno_Crafted.png'},
    {name: 'Pirinsko', brewery: 'Pirinsko', country: 'Bulgaria', continent: 'Europe', image: 'img/Bulgaria/Pirinsko/Pirinsko_1.png'},
    {name: 'Pirinsko', brewery: 'Pirinsko', country: 'Bulgaria', continent: 'Europe', image: 'img/Bulgaria/Pirinsko/Pirinsko_2.png'},
    {name: 'Pirinsko', brewery: 'Pirinsko', country: 'Bulgaria', continent: 'Europe', image: 'img/Bulgaria/Pirinsko/Pirinsko_3.png'},
    {name: 'Pirinsko </br> Mlado Pivo', brewery: 'Pirinsko', country: 'Bulgaria', continent: 'Europe', image: 'img/Bulgaria/Pirinsko/Pirinsko_Mlado_Pivo.png'},
    {name: 'Bolyarka', brewery: 'Bolyarka', country: 'Bulgaria', continent: 'Europe', image: 'img/Bulgaria/Bolyarka/Bolyarka.png'},
    {name: 'Balkansko', brewery: 'Bolyarka', country: 'Bulgaria', continent: 'Europe', image: 'img/Bulgaria/Bolyarka/Balkansko.png'},
    {name: 'Burgasko', brewery: 'Burgasko', country: 'Bulgaria', continent: 'Europe', image: 'img/Bulgaria/Burgasko/Burgasko.png'},
    {name: 'Almus', brewery: 'Lomsko Pivo', country: 'Bulgaria', continent: 'Europe', image: 'img/Bulgaria/Almus/Almus.png'},
    {name: 'Ambrosius', brewery: 'Bolyarka', country: 'Bulgaria', continent: 'Europe', image: 'img/Bulgaria/Bolyarka/Ambrosius.png'},
    {name: 'Glarus', brewery: 'Glarus', country: 'Bulgaria', continent: 'Europe', image: 'img/Bulgaria/Glarus/Glarus.png'},
    {name: 'Shumensko', brewery: 'Shumensko', country: 'Bulgaria', continent: 'Europe', image: 'img/Bulgaria/Shumensko/Shumensko_1.png'},
    {name: 'Shumensko', brewery: 'Shumensko', country: 'Bulgaria', continent: 'Europe', image: 'img/Bulgaria/Shumensko/Shumensko_2.png'},
    {name: 'Shumensko Pivo', brewery: 'Shumensko', country: 'Bulgaria', continent: 'Europe', image: 'img/Bulgaria/Shumensko/Shumensko_Pivo.png'},
];