const beerBulgaria = [
    {name: 'Zagorka', brewery: 'Zagorka', country: 'Bulgaria', continent: 'Europe', image: 'img/Bulgaria/1.png'},
    {name: 'Zagorka', brewery: 'Zagorka', country: 'Bulgaria', continent: 'Europe', image: 'img/Bulgaria/2.png'},
    {name: 'Zagorka', brewery: 'Zagorka', country: 'Bulgaria', continent: 'Europe', image: 'img/Bulgaria/3.png'},
    {name: 'Zagorka </br> Special', brewery: 'Zagorka', country: 'Bulgaria', continent: 'Europe', image: 'img/Bulgaria/4.png'},
    {name: 'Kamenitza', brewery: 'Kamenitza', country: 'Bulgaria', continent: 'Europe', image: 'img/Bulgaria/5.png'},
    {name: 'Kamenitza', brewery: 'Kamenitza', country: 'Bulgaria', continent: 'Europe', image: 'img/Bulgaria/6.png'},
    {name: 'Kamenitza', brewery: 'Kamenitza', country: 'Bulgaria', continent: 'Europe', image: 'img/Bulgaria/7.png'},
    {name: 'Kamenitza', brewery: 'Kamenitza', country: 'Bulgaria', continent: 'Europe', image: 'img/Bulgaria/8.png'},
    {name: 'Kamenitza', brewery: 'Kamenitza', country: 'Bulgaria', continent: 'Europe', image: 'img/Bulgaria/9.png'},
    {name: 'Kamenitza </br> Dark', brewery: 'Kamenitza', country: 'Bulgaria', continent: 'Europe', image: 'img/Bulgaria/10.png'},
    {name: 'Ariana', brewery: 'Ariana', country: 'Bulgaria', continent: 'Europe', image: 'img/Bulgaria/11.png'},
    {name: 'Ariana', brewery: 'Ariana', country: 'Bulgaria', continent: 'Europe', image: 'img/Bulgaria/12.png'},
    {name: 'Stolichno </br> Weiss', brewery: 'Stolichno', country: 'Bulgaria', continent: 'Europe', image: 'img/Bulgaria/13.png'},
    {name: 'Stolichno </br> Bock', brewery: 'Stolichno', country: 'Bulgaria', continent: 'Europe', image: 'img/Bulgaria/14.png'},
    {name: 'Stolichno </br> Pale Bock', brewery: 'Stolichno', country: 'Bulgaria', continent: 'Europe', image: 'img/Bulgaria/15.png'},
    {name: 'Stolichno </br> Crafted Quality', brewery: 'Stolichno', country: 'Bulgaria', continent: 'Europe', image: 'img/Bulgaria/16.png'},
    {name: 'Pirinsko', brewery: 'Pirinsko', country: 'Bulgaria', continent: 'Europe', image: 'img/Bulgaria/17.png'},
    {name: 'Pirinsko', brewery: 'Pirinsko', country: 'Bulgaria', continent: 'Europe', image: 'img/Bulgaria/18.png'},
    {name: 'Pirinsko', brewery: 'Pirinsko', country: 'Bulgaria', continent: 'Europe', image: 'img/Bulgaria/19.png'},
    {name: 'Pirinsko </br> Mlado Pivo', brewery: 'Pirinsko', country: 'Bulgaria', continent: 'Europe', image: 'img/Bulgaria/20.png'},
    {name: 'Bolyarka', brewery: 'Bolyarka', country: 'Bulgaria', continent: 'Europe', image: 'img/Bulgaria/21.png'},
    {name: 'Balkansko', brewery: 'Bolyarka', country: 'Bulgaria', continent: 'Europe', image: 'img/Bulgaria/22.png'},
    {name: 'Burgasko', brewery: 'Burgasko', country: 'Bulgaria', continent: 'Europe', image: 'img/Bulgaria/23.png'},
    {name: 'Almus', brewery: 'Lomsko Pivo', country: 'Bulgaria', continent: 'Europe', image: 'img/Bulgaria/24.png'},
    {name: 'Ambrosius', brewery: 'Bolyarka', country: 'Bulgaria', continent: 'Europe', image: 'img/Bulgaria/25.png'},
    {name: 'Glarus', brewery: 'Glarus', country: 'Bulgaria', continent: 'Europe', image: 'img/Bulgaria/26.png'},
    {name: 'Shumensko', brewery: 'Shumensko', country: 'Bulgaria', continent: 'Europe', image: 'img/Bulgaria/27.png'},
    {name: 'Shumensko', brewery: 'Shumensko', country: 'Bulgaria', continent: 'Europe', image: 'img/Bulgaria/28.png'},
    {name: 'Shumensko', brewery: 'Shumensko', country: 'Bulgaria', continent: 'Europe', image: 'img/Bulgaria/29.png'},
];