const beerCzechia = [
    {name: 'Staropramen 11', brewery: 'Staropramen', country: 'Czechia', continent: 'Europe', image: 'img/Czechia/Staropramen/Staropramen_11.png'},
    {name: 'Staropramen', brewery: 'Staropramen', country: 'Czechia', continent: 'Europe', image: 'img/Czechia/Staropramen/Staropramen_1.png'},
    {name: 'Staropramen Svetly', brewery: 'Staropramen', country: 'Czechia', continent: 'Europe', image: 'img/Czechia/3.png'},
    {name: 'Staropramen', brewery: 'Staropramen', country: 'Czechia', continent: 'Europe', image: 'img/Czechia/Staropramen/Staropramen_2.png'},
    {name: 'Staropramen', brewery: 'Staropramen', country: 'Czechia', continent: 'Europe', image: 'img/Czechia/Staropramen/Staropramen_3.png'},
    {name: 'Staropramen ??', brewery: 'Staropramen', country: 'Czechia', continent: 'Europe', image: 'img/Czechia/Staropramen/Staropramen_4.png'},
    {name: 'Bernard 11 Nepasterovano', brewery: 'Pivovar Bernard', country: 'Czechia', continent: 'Europe', image: 'img/Czechia/7.png'},
    {name: 'Bernard 12 Nepasterovano', brewery: 'Pivovar Bernard', country: 'Czechia', continent: 'Europe', image: 'img/Czechia/Bernard/Bernard_12.png'},
    {name: 'Kozel Svetly', brewery: 'Pivovar Velke Popovice', country: 'Czechia', continent: 'Europe', image: 'img/Czechia/Kozel/Kozel_Svetly.png'},
    {name: 'Kozel Cerny', brewery: 'Pivovar Velke Popovice', country: 'Czechia', continent: 'Europe', image: 'img/Czechia/Kozel/Kozel_Cerny.png'},
    {name: 'Kozel 11', brewery: 'Pivovar Velke Popovice', country: 'Czechia', continent: 'Europe', image: 'img/Czechia/Kozel/Kozel_11.png'},
    {name: 'Bohemia Regent', brewery: 'Pivovar Regent', country: 'Czechia', continent: 'Europe', image: 'img/Czechia/Regent/Bohemia_Regent.png'},
    {name: 'Krušovice 10', brewery: 'Královský Pivovar Krušovice', country: 'Czechia', continent: 'Europe', image: 'img/Czechia/13.png'},
    {name: 'Gambrinus', brewery: 'Gambrinus', country: 'Czechia', continent: 'Europe', image: 'img/Czechia/Gambrinus/Gambrinus_1.png'},
    {name: 'Gambrinus', brewery: 'Gambrinus', country: 'Czechia', continent: 'Europe', image: 'img/Czechia/Gambrinus/Gambrinus_2.png'},
    {
        name: 'Gambrinus Excelent Extra Chmeleny',
        brewery: 'Gambrinus',
        country: 'Czechia',
        continent: 'Europe',
        image: 'img/Czechia/Gambrinus/Gambrinus_X.png'
    },
    {name: 'Braník', brewery: 'Pivovary Staropramen', country: 'Czechia', continent: 'Europe', image: 'img/Czechia/17.png'},
    {name: 'Březňák', brewery: 'Pivovar Velké Březno', country: 'Czechia', continent: 'Europe', image: 'img/Czechia/Breznak/Breznak.png'},
    {name: 'Bakalář', brewery: 'Pivovar Rakovník', country: 'Czechia', continent: 'Europe', image: 'img/Czechia/Bakalar/Bakalar.png'},
    {name: 'Primus', brewery: 'Primus', country: 'Czechia', continent: 'Europe', image: 'img/Czechia/Primus/Primus.png'},
    {name: 'Klasik', brewery: 'Klasik', country: 'Czechia', continent: 'Europe', image: 'img/Czechia/21.png'},
    {name: 'Poutnik Svetly Lezak Premium', brewery: 'Pivovar Pelhrimov', country: 'Czechia', continent: 'Europe', image: 'img/Czechia/Poutnik/Poutnik_Svetly.png'},
    {name: 'Krušovice Lezak', brewery: 'Královský Pivovar Krušovice', country: 'Czechia', continent: 'Europe', image: 'img/Czechia/Krusovice/Krusovice_Lezak.png'},
    {name: 'Pardal Echt', brewery: 'Budweiser Budvar', country: 'Czechia', continent: 'Europe', image: 'img/Czechia/BudweiserBudvar/Pardal_Echt.png'},
    {name: 'Starobrno', brewery: 'Pivovar Starobrno', country: 'Czechia', continent: 'Europe', image: 'img/Czechia/Starobrno/Starobrno.png'},
    {name: 'Birell Svetly', brewery: 'Birell', country: 'Czechia', continent: 'Europe', image: 'img/Czechia/Birell/Birell_Svetly.png'},
    {name: 'Pilsner Urquell', brewery: 'Pilsner Urquell', country: 'Czechia', continent: 'Europe', image: 'img/Czechia/PilsnerUrquell/Pilsner_Urquell.png'},
    {name: 'Svijany Bez Pasterizace ??', brewery: 'Pivovar Svijany', country: 'Czechia', continent: 'Europe', image: 'img/Czechia/Svijany/Svijany_1.png'},
    {name: 'Svijany Bez Pasterizace ??', brewery: 'Pivovar Svijany', country: 'Czechia', continent: 'Europe', image: 'img/Czechia/Svijany/Svijany_2.png'},
    {name: 'Svijany Bez Pasterizace ??', brewery: 'Pivovar Svijany', country: 'Czechia', continent: 'Europe', image: 'img/Czechia/Svijany/Svijany_3.png'},
    {name: 'Primátor W', brewery: 'Pivovar Náchod', country: 'Czechia', continent: 'Europe', image: 'img/Czechia/Primator/Primator_W.png'},
    {name: 'Budweiser Budvar Tmavy Lezak', brewery: 'Budweiser Budvar', country: 'Czechia', continent: 'Europe', image: 'img/Czechia/BudweiserBudvar/Budweiser_Budvar.png'},
    {name: 'Praga', brewery: 'Praga', country: 'Czechia', continent: 'Europe', image: 'img/Czechia/Praga/Praga.png'},
];