const beerCzechia = [
    {name: 'Staropramen 11', brewery: 'Staropramen', country: 'Czechia', continent: 'Europe', image: 'img/Czechia/1.png'},
    {name: 'Staropramen', brewery: 'Staropramen', country: 'Czechia', continent: 'Europe', image: 'img/Czechia/2.png'},
    {name: 'Staropramen Svetly', brewery: 'Staropramen', country: 'Czechia', continent: 'Europe', image: 'img/Czechia/3.png'},
    {name: 'Staropramen', brewery: 'Staropramen', country: 'Czechia', continent: 'Europe', image: 'img/Czechia/4.png'},
    {name: 'Staropramen', brewery: 'Staropramen', country: 'Czechia', continent: 'Europe', image: 'img/Czechia/5.png'},
    {name: 'Staropramen ??', brewery: 'Staropramen', country: 'Czechia', continent: 'Europe', image: 'img/Czechia/6.png'},
    {name: 'Bernard 11 Nepasterovano', brewery: 'Pivovar Bernard', country: 'Czechia', continent: 'Europe', image: 'img/Czechia/7.png'},
    {name: 'Bernard 12 Nepasterovano', brewery: 'Pivovar Bernard', country: 'Czechia', continent: 'Europe', image: 'img/Czechia/8.png'},
    {name: 'Kozel Svetly', brewery: 'Pivovar Velke Popovice', country: 'Czechia', continent: 'Europe', image: 'img/Czechia/9.png'},
    {name: 'Kozel Cerny', brewery: 'Pivovar Velke Popovice', country: 'Czechia', continent: 'Europe', image: 'img/Czechia/10.png'},
    {name: 'Kozel 11', brewery: 'Pivovar Velke Popovice', country: 'Czechia', continent: 'Europe', image: 'img/Czechia/11.png'},
    {name: 'Bohemia Regent', brewery: 'Pivovar Regent', country: 'Czechia', continent: 'Europe', image: 'img/Czechia/12.png'},
    {name: 'Krusovice 10', brewery: 'Královský Pivovar Krušovice', country: 'Czechia', continent: 'Europe', image: 'img/Czechia/13.png'},
    {name: 'Gambrinus', brewery: 'Plzeňský prazdroj', country: 'Czechia', continent: 'Europe', image: 'img/Czechia/14.png'},
    {name: 'Gambrinus', brewery: 'Plzeňský prazdroj', country: 'Czechia', continent: 'Europe', image: 'img/Czechia/15.png'},
    {
        name: 'Gambrinus Excelent Extra Chmeleny',
        brewery: 'Plzeňský prazdroj',
        country: 'Czechia',
        continent: 'Europe',
        image: 'img/Czechia/16.png'
    },
    {name: 'Braník', brewery: 'Pivovary Staropramen', country: 'Czechia', continent: 'Europe', image: 'img/Czechia/17.png'},
    {name: 'Březňák', brewery: 'Pivovar Velké Březno', country: 'Czechia', continent: 'Europe', image: 'img/Czechia/18.png'},
    {name: 'Bakalář', brewery: 'Pivovar Rakovník', country: 'Czechia', continent: 'Europe', image: 'img/Czechia/19.png'},
    {name: 'Primus', brewery: 'Plzeňský prazdroj', country: 'Czechia', continent: 'Europe', image: 'img/Czechia/20.png'},
    {name: 'Klasik', brewery: 'Plzeňský prazdroj', country: 'Czechia', continent: 'Europe', image: 'img/Czechia/21.png'},
    {name: 'Poutnik Svetly Lezak Premium', brewery: 'Pivovar Pelhrimov', country: 'Czechia', continent: 'Europe', image: 'img/Czechia/22.png'},
    {name: 'Krusovice Lezak', brewery: 'Královský Pivovar Krušovice', country: 'Czechia', continent: 'Europe', image: 'img/Czechia/23.png'},
    {name: 'Pardal Echt', brewery: 'Budweiser Budvar', country: 'Czechia', continent: 'Europe', image: 'img/Czechia/24.png'},
    {name: 'Starobrno', brewery: 'Pivovar Starobrno', country: 'Czechia', continent: 'Europe', image: 'img/Czechia/25.png'},
    {name: 'Birell Svetly', brewery: 'Plzeňský prazdroj', country: 'Czechia', continent: 'Europe', image: 'img/Czechia/26.png'},
    {name: 'Pilsner Urquell', brewery: 'Plzeňský prazdroj', country: 'Czechia', continent: 'Europe', image: 'img/Czechia/27.png'},
    {name: 'Svijany Bez Pasterizace ??', brewery: 'Pivovar Svijany', country: 'Czechia', continent: 'Europe', image: 'img/Czechia/28.png'},
    {name: 'Svijany Bez Pasterizace ??', brewery: 'Pivovar Svijany', country: 'Czechia', continent: 'Europe', image: 'img/Czechia/29.png'},
    {name: 'Svijany Bez Pasterizace ??', brewery: 'Pivovar Svijany', country: 'Czechia', continent: 'Europe', image: 'img/Czechia/30.png'},
    {name: 'Primátor W', brewery: 'Pivovar Náchod', country: 'Czechia', continent: 'Europe', image: 'img/Czechia/31.png'},
    {name: 'Budweiser Budvar Tmavy Lezak', brewery: 'Budweiser Budvar', country: 'Czechia', continent: 'Europe', image: 'img/Czechia/32.png'},
];