const beerDenmark = [
    {name: 'Tuborg </br> Classic', brewery: 'Tuborg', country: 'Denmark', continent: 'Europe', image: 'img/Denmark/1.png'},
    {name: 'Tuborg </br> Fine Festival', brewery: 'Tuborg', country: 'Denmark', continent: 'Europe', image: 'img/Denmark/2.png'},
    {name: 'Tuborg </br> Paskebrygg Kylle Kylle', brewery: 'Tuborg', country: 'Denmark', continent: 'Europe', image: 'img/Denmark/3.png'},
    {name: 'KB </br> Hvidtol', brewery: 'Tuborg', country: 'Denmark', continent: 'Europe', image: 'img/Denmark/18.png'},
    {name: 'Carlsberg </br> Elephant', brewery: 'Carlsberg', country: 'Denmark', continent: 'Europe', image: 'img/Denmark/4.png'},
    {name: 'Carlsberg', brewery: 'Carlsberg', country: 'Denmark', continent: 'Europe', image: 'img/Denmark/5.png'},
    {name: 'Albani </br> Pilsner', brewery: 'Albani', country: 'Denmark', continent: 'Europe', image: 'img/Denmark/6.png'},
    {name: 'Albani </br> Classic', brewery: 'Albani', country: 'Denmark', continent: 'Europe', image: 'img/Denmark/7.png'},
    {name: 'Albani </br> Giraf Beer', brewery: 'Albani', country: 'Denmark', continent: 'Europe', image: 'img/Denmark/8.png'},
    {name: 'Albani </br> Påske Bryg', brewery: 'Albani', country: 'Denmark', continent: 'Europe', image: 'img/Denmark/9.png'},
    {name: 'Ceres Royal </br> Classic', brewery: 'Ceres', country: 'Denmark', continent: 'Europe', image: 'img/Denmark/10.png'},
    {name: 'Ceres Royal </br> Pilsner', brewery: 'Ceres', country: 'Denmark', continent: 'Europe', image: 'img/Denmark/11.png'},
    {name: 'Ceres </br> Hvidtøl', brewery: 'Ceres', country: 'Denmark', continent: 'Europe', image: 'img/Denmark/12.png'},
    {name: 'Harboe </br> Pilsner', brewery: 'Harboe', country: 'Denmark', continent: 'Europe', image: 'img/Denmark/13.png'},
    {name: 'Harboe', brewery: 'Harboe', country: 'Denmark', continent: 'Europe', image: 'img/Denmark/14.png'},
    {name: 'Bryghuset </br> Braunstein', brewery: 'Bryghuset Braunstein', country: 'Denmark', continent: 'Europe', image: 'img/Denmark/15.png'},
    {name: 'Skovlyst </br> India Pale Ale', brewery: 'Bryggeri  Skovlyst', country: 'Denmark', continent: 'Europe', image: 'img/Denmark/16.png'},
    {name: 'Wiibroe </br> Porter', brewery: 'Wiibroe', country: 'Denmark', continent: 'Europe', image: 'img/Denmark/17.png'},
];