const beerDenmark = [
    {name: 'Tuborg </br> Classic', brewery: 'Tuborg', country: 'Denmark', continent: 'Europe', image: 'img/Denmark/Tuborg/Tuborg_Classic.png'},
    {name: 'Tuborg </br> Fine Festival', brewery: 'Tuborg', country: 'Denmark', continent: 'Europe', image: 'img/Denmark/Tuborg/Tuborg_Fine_Festival.png'},
    {name: 'Tuborg </br> Paskebrygg Kylle Kylle', brewery: 'Tuborg', country: 'Denmark', continent: 'Europe', image: 'img/Denmark/Tuborg/Tuborg_Paskebrygg.png'},
    {name: 'KB </br> Hvidtol', brewery: 'Tuborg', country: 'Denmark', continent: 'Europe', image: 'img/Denmark/Tuborg/KB_Hvidtol.png'},
    {name: 'Carlsberg </br> Elephant', brewery: 'Carlsberg', country: 'Denmark', continent: 'Europe', image: 'img/Denmark/Carlsberg/Carlsberg_Elephant.png'},
    {name: 'Carlsberg', brewery: 'Carlsberg', country: 'Denmark', continent: 'Europe', image: 'img/Denmark/Carlsberg/Carlsberg.png'},
    {name: 'Albani </br> Pilsner', brewery: 'Albani', country: 'Denmark', continent: 'Europe', image: 'img/Denmark/Albani/Albani_Pilsner.png'},
    {name: 'Albani </br> Classic', brewery: 'Albani', country: 'Denmark', continent: 'Europe', image: 'img/Denmark/Albani/Albani_Classic.png'},
    {name: 'Albani </br> Giraf Beer', brewery: 'Albani', country: 'Denmark', continent: 'Europe', image: 'img/Denmark/Albani/Albani_Giraf_Beer.png'},
    {name: 'Albani </br> Påske Bryg', brewery: 'Albani', country: 'Denmark', continent: 'Europe', image: 'img/Denmark/Albani/Albani_Paske_Bryg.png'},
    {name: 'Ceres Royal </br> Classic', brewery: 'Ceres', country: 'Denmark', continent: 'Europe', image: 'img/Denmark/Ceres/Ceres_Royal_Classic.png'},
    {name: 'Ceres Royal </br> Pilsner', brewery: 'Ceres', country: 'Denmark', continent: 'Europe', image: 'img/Denmark/Ceres/Ceres_Royal_Pilsner.png'},
    {name: 'Ceres </br> Hvidtøl', brewery: 'Ceres', country: 'Denmark', continent: 'Europe', image: 'img/Denmark/Ceres/Ceres_Hvidtol.png'},
    {name: 'Harboe </br> Pilsner', brewery: 'Harboe', country: 'Denmark', continent: 'Europe', image: 'img/Denmark/Harboe/Harboe_Pilsner.png'},
    {name: 'Harboe', brewery: 'Harboe', country: 'Denmark', continent: 'Europe', image: 'img/Denmark/Harboe/Harboe.png'},
    {name: 'Bryghuset </br> Braunstein', brewery: 'Bryghuset Braunstein', country: 'Denmark', continent: 'Europe', image: 'img/Denmark/BryghusetBraunstein/Bryghuset_Braunstein.png'},
    {name: 'Skovlyst </br> India Pale Ale', brewery: 'Bryggeri  Skovlyst', country: 'Denmark', continent: 'Europe', image: 'img/Denmark/Skovlyst/Skovlyst_IPA.png'},
    {name: 'Wiibroe </br> Porter', brewery: 'Wiibroe', country: 'Denmark', continent: 'Europe', image: 'img/Denmark/Wiibroe/Wiibroe_Porter.png'},
];