const beerGermany = [
    {name: 'Warsteiner Premium Pilsener', brewery: 'Warsteiner', country: 'Germany', continent: 'Europe', image: 'img/Germany/Warsteiner/Warsteiner_Premium_Pilsener.png'},
    {name: 'Warsteiner Pilsener', brewery: 'Warsteiner', country: 'Germany', continent: 'Europe', image: 'img/Germany/Warsteiner/Warsteiner_Pilsener.png'},
    {name: 'Warsteiner Radler Zitrone', brewery: 'Warsteiner', country: 'Germany', continent: 'Europe', image: 'img/Germany/Warsteiner/Warsteiner_Radler_Zitrone.png'},
    {name: 'Warsteiner Radler', brewery: 'Warsteiner', country: 'Germany', continent: 'Europe', image: 'img/Germany/Warsteiner/Warsteiner_Radler_1.png'},
    {name: 'Warsteiner Radler', brewery: 'Warsteiner', country: 'Germany', continent: 'Europe', image: 'img/Germany/Warsteiner/Warsteiner_Radler_2.png'},
    {name: 'Warsteiner Meisterstück', brewery: 'Warsteiner', country: 'Germany', continent: 'Europe', image: 'img/Germany/Warsteiner/Warsteiner_Meisterstuck.png'},
    {name: 'Beck\'s', brewery: 'Beck\'s', country: 'Germany', continent: 'Europe', image: 'img/Germany/Becks/Becks_1.png'},
    {name: 'Beck\'s', brewery: 'Beck\'s', country: 'Germany', continent: 'Europe', image: 'img/Germany/Becks/Becks_2.png'},
    {name: 'Heidelberger 1603', brewery: 'Heidelberger', country: 'Germany', continent: 'Europe', image: 'img/Germany/Heidelberger/Heidelberger_1603.png'},
    {name: 'Heidelberger Export', brewery: 'Heidelberger', country: 'Germany', continent: 'Europe', image: 'img/Germany/Heidelberger/Heidelberger_Export.png'},
    {name: 'Heidelberger Pils', brewery: 'Heidelberger', country: 'Germany', continent: 'Europe', image: 'img/Germany/Heidelberger/Heidelberger_Pils.png'},
    {name: 'Deutsches Bier', brewery: 'Deutsches Bier', country: 'Germany', continent: 'Europe', image: 'img/Germany/Others/Deutsches Bier_1.png'},
    {name: 'Deutsches Bier', brewery: 'Deutsches Bier', country: 'Germany', continent: 'Europe', image: 'img/Germany/Others/Deutsches Bier_2.png'},
    {name: 'Deutsches Bier', brewery: 'Deutsches Bier', country: 'Germany', continent: 'Europe', image: 'img/Germany/Others/Deutsches Bier_3.png'},
    {name: 'Jever Pilsener', brewery: 'Jever', country: 'Germany', continent: 'Europe', image: 'img/Germany/Jever/Jever_Pilsener.png'},
    {name: 'Jever Light', brewery: 'Jever', country: 'Germany', continent: 'Europe', image: 'img/Germany/Jever/Jever_Light.png'},
    {name: 'Clausthaler Classic', brewery: 'Clausthaler', country: 'Germany', continent: 'Europe', image: 'img/Germany/Clausthaler/Clausthaler_Classic.png'},
    {name: 'Clausthaler Extra Herb', brewery: 'Clausthaler', country: 'Germany', continent: 'Europe', image: 'img/Germany/Clausthaler/Clausthaler_Extra_Herb.png'},
    {name: 'Schöfferhofer Hefeweizen', brewery: 'Schöfferhofer', country: 'Germany', continent: 'Europe', image: 'img/Germany/Schofferhofer/Schofferhofer_Hefeweizen.png'},
    {name: 'Schöfferhofer Hefeweizen Grapefruit', brewery: 'Schöfferhofer', country: 'Germany', continent: 'Europe', image: 'img/Germany/Schofferhofer/Schofferhofer_Hefeweizen_Grapefruit.png'},
    {name: 'Wernesgrüner Pils', brewery: 'Wernesgrüner', country: 'Germany', continent: 'Europe', image: 'img/Germany/Others/Wernesgruner_1.png'},
    {name: 'Wernesgrüner Pils', brewery: 'Wernesgrüner', country: 'Germany', continent: 'Europe', image: 'img/Germany/Others/Wernesgruner_2.png'},
    {name: 'Hasseröder', brewery: 'Hasseröder', country: 'Germany', continent: 'Europe', image: 'img/Germany/Others/Hasseroder.png'},
    {name: 'Diebels', brewery: 'Diebels', country: 'Germany', continent: 'Europe', image: 'img/Germany/Others/Diebels.png'},
    {name: 'Rothaus', brewery: 'Rothaus', country: 'Germany', continent: 'Europe', image: 'img/Germany/Others/Rothaus.png'},
    {name: 'Eichbaum Pilsener', brewery: 'Eichbaum', country: 'Germany', continent: 'Europe', image: 'img/Germany/Others/Eichbaum_Pilsener.png'},
    {name: 'Holsten', brewery: 'Holsten', country: 'Germany', continent: 'Europe', image: 'img/Germany/Others/Holsten.png'},
    {name: 'Früh Kölsch', brewery: 'Früh Kölsch', country: 'Germany', continent: 'Europe', image: 'img/Germany/Others/Fruh_Kolsch.png'},
    {name: 'Dom Kölsch', brewery: 'Dom Kölsch', country: 'Germany', continent: 'Europe', image: 'img/Germany/Others/Dom_Kolsch.png'},
    {name: 'Mühlen Kölsch', brewery: 'Mühlen Kölsch', country: 'Germany', continent: 'Europe', image: 'img/Germany/Others/Muhlen_Kolsch.png'},
    {name: 'Gaffel Kölsch', brewery: 'Gaffel Kölsch', country: 'Germany', continent: 'Europe', image: 'img/Germany/Others/Gaffel_Kolsch.png'},
    {name: 'Koblenzer', brewery: 'Koblenzer', country: 'Germany', continent: 'Europe', image: 'img/Germany/Others/Koblenzer.png'},
    {name: 'Einbecker Pilsener', brewery: 'Einbecker', country: 'Germany', continent: 'Europe', image: 'img/Germany/Others/Einbecker_Pilsener.png'},
    {name: 'Berg', brewery: 'Berg', country: 'Germany', continent: 'Europe', image: 'img/Germany/Others/Berg.png'},
    {name: 'Härle Export Gold', brewery: 'Härle', country: 'Germany', continent: 'Europe', image: 'img/Germany/Others/Harle_Export_Gold.png'},
    {name: 'Härle Weisse', brewery: 'Härle', country: 'Germany', continent: 'Europe', image: 'img/Germany/Others/Harle_Weisse.png'},
    {name: 'Krombacher Weizen', brewery: 'Krombacher', country: 'Germany', continent: 'Europe', image: 'img/Germany/Others/Krombacher_Weizen.png'},
    {name: 'Bitburger Premium Pils', brewery: 'Bitburger', country: 'Germany', continent: 'Europe', image: 'img/Germany/Bitburger/Bitburger_Premium_Pils.png'},
    {name: 'Bitburger Fan Force One', brewery: 'Bitburger', country: 'Germany', continent: 'Europe', image: 'img/Germany/Bitburger/Bitburger_Fan_Force_One.png'},
    {name: 'Bitburger Alkoholfrei Radler', brewery: 'Bitburger', country: 'Germany', continent: 'Europe', image: 'img/Germany/Bitburger/Bitburger_Alkoholfrei_Radler.png'},
    {name: 'Bitburger Alkoholfrei Pils', brewery: 'Bitburger', country: 'Germany', continent: 'Europe', image: 'img/Germany/Bitburger/Bitburger_Alkoholfrei_Pils.png'},
    {name: 'BRLO Berliner Weisse', brewery: 'BRLO', country: 'Germany', continent: 'Europe', image: 'img/Germany/Others/BRLO.png'},
    {name: 'Ratsherrn Just craft real taste', brewery: 'Ratsherrn', country: 'Germany', continent: 'Europe', image: 'img/Germany/Others/Ratsherrn.png'},
    {name: 'Gruthaus', brewery: 'Gruthaus', country: 'Germany', continent: 'Europe', image: 'img/Germany/Others/Gruthaus.png'},
    {name: 'Kehrwieder Prototyp', brewery: 'Kehrwieder', country: 'Germany', continent: 'Europe', image: 'img/Germany/Others/Kehrwieder.png'},
    {name: 'Astra Urtyp', brewery: 'Astra', country: 'Germany', continent: 'Europe', image: 'img/Germany/Others/Astra_Urtyp.png'},
    {name: 'Herrenhäuser', brewery: 'Herrenhäuser', country: 'Germany', continent: 'Europe', image: 'img/Germany/Others/Herrenhauser.png'},
    {name: 'Perlenbacher', brewery: 'Perlenbacher', country: 'Germany', continent: 'Europe', image: 'img/Germany/Others/Perlenbacher.png'},
    {name: 'Riegeler', brewery: 'Riegeler', country: 'Germany', continent: 'Europe', image: 'img/Germany/Others/Riegeler.png'},
    {name: 'Sachsengold Landbier', brewery: 'Sachsengold Landbier', country: 'Germany', continent: 'Europe', image: 'img/Germany/Others/Sachsengold.png'},
    {name: 'Gold Ochsen', brewery: 'Gold Ochsen', country: 'Germany', continent: 'Europe', image: 'img/Germany/Others/Gold_Ochsen.png'},
    {name: 'Farny', brewery: 'Farny', country: 'Germany', continent: 'Europe', image: 'img/Germany/Others/Farny.png'},
    {name: 'Zoller Hof </br> Nein! Zu Fracking', brewery: 'Zoller Hof', country: 'Germany', continent: 'Europe', image: 'img/Germany/Others/Zoller_Hof.png'},
    {name: 'Patronus Weissbier', brewery: 'Patronus', country: 'Germany', continent: 'Europe', image: 'img/Germany/Others/Patronus.png'},
];