const beerGermany = [
    {name: 'Warsteiner Premium Pilsener', brewery: 'Warsteiner', country: 'Germany', continent: 'Europe', image: 'img/Germany/1.png'},
    {name: 'Warsteiner Pilsener', brewery: 'Warsteiner', country: 'Germany', continent: 'Europe', image: 'img/Germany/2.png'},
    {name: 'Warsteiner Radler Zitrone', brewery: 'Warsteiner', country: 'Germany', continent: 'Europe', image: 'img/Germany/3.png'},
    {name: 'Warsteiner Radler', brewery: 'Warsteiner', country: 'Germany', continent: 'Europe', image: 'img/Germany/4.png'},
    {name: 'Warsteiner Radler', brewery: 'Warsteiner', country: 'Germany', continent: 'Europe', image: 'img/Germany/5.png'},
    {name: 'Warsteiner Meisterstück', brewery: 'Warsteiner', country: 'Germany', continent: 'Europe', image: 'img/Germany/6.png'},
    {name: 'Beck\'s', brewery: 'Beck\'s', country: 'Germany', continent: 'Europe', image: 'img/Germany/7.png'},
    {name: 'Beck\'s', brewery: 'Beck\'s', country: 'Germany', continent: 'Europe', image: 'img/Germany/8.png'},
    {name: 'Heidelberger 1603', brewery: 'Heidelberger', country: 'Germany', continent: 'Europe', image: 'img/Germany/9.png'},
    {name: 'Heidelberger Export', brewery: 'Heidelberger', country: 'Germany', continent: 'Europe', image: 'img/Germany/10.png'},
    {name: 'Heidelberger Pils', brewery: 'Heidelberger', country: 'Germany', continent: 'Europe', image: 'img/Germany/11.png'},
    {name: 'Deutsches Bier', brewery: 'Deutsches Bier', country: 'Germany', continent: 'Europe', image: 'img/Germany/Others/Deutsches Bier_1.png'},
    {name: 'Deutsches Bier', brewery: 'Deutsches Bier', country: 'Germany', continent: 'Europe', image: 'img/Germany/Others/Deutsches Bier_2.png'},
    {name: 'Deutsches Bier', brewery: 'Deutsches Bier', country: 'Germany', continent: 'Europe', image: 'img/Germany/Others/Deutsches Bier_3.png'},
    {name: 'Jever Pilsener', brewery: 'Jever', country: 'Germany', continent: 'Europe', image: 'img/Germany/15.png'},
    {name: 'Jever Light', brewery: 'Jever', country: 'Germany', continent: 'Europe', image: 'img/Germany/16.png'},
    {name: 'Clausthaler Classic', brewery: 'Clausthaler', country: 'Germany', continent: 'Europe', image: 'img/Germany/17.png'},
    {name: 'Clausthaler Extra Herb', brewery: 'Clausthaler', country: 'Germany', continent: 'Europe', image: 'img/Germany/18.png'},
    {name: 'Schöfferhofer Hefeweizen', brewery: 'Schöfferhofer', country: 'Germany', continent: 'Europe', image: 'img/Germany/19.png'},
    {name: 'Schöfferhofer Hefeweizen Grapefruit', brewery: 'Schöfferhofer', country: 'Germany', continent: 'Europe', image: 'img/Germany/20.png'},
    {name: 'Wernesgrüner Pils', brewery: 'Wernesgrüner', country: 'Germany', continent: 'Europe', image: 'img/Germany/21.png'},
    {name: 'Wernesgrüner Pils', brewery: 'Wernesgrüner', country: 'Germany', continent: 'Europe', image: 'img/Germany/22.png'},
    {name: 'Hasseröder', brewery: 'Hasseröder', country: 'Germany', continent: 'Europe', image: 'img/Germany/23.png'},
    {name: 'Diebels', brewery: 'Diebels', country: 'Germany', continent: 'Europe', image: 'img/Germany/24.png'},
    {name: 'Rothaus', brewery: 'Rothaus', country: 'Germany', continent: 'Europe', image: 'img/Germany/25.png'},
    {name: 'Eichbaum Pilsener', brewery: 'Eichbaum', country: 'Germany', continent: 'Europe', image: 'img/Germany/26.png'},
    {name: 'Holsten', brewery: 'Holsten', country: 'Germany', continent: 'Europe', image: 'img/Germany/27.png'},
    {name: 'Früh Kölsch', brewery: 'Früh Kölsch', country: 'Germany', continent: 'Europe', image: 'img/Germany/28.png'},
    {name: 'Dom Kölsch', brewery: 'Dom Kölsch', country: 'Germany', continent: 'Europe', image: 'img/Germany/29.png'},
    {name: 'Mühlen Kölsch', brewery: 'Mühlen Kölsch', country: 'Germany', continent: 'Europe', image: 'img/Germany/30.png'},
    {name: 'Gaffel Kölsch', brewery: 'Gaffel Kölsch', country: 'Germany', continent: 'Europe', image: 'img/Germany/31.png'},
    {name: 'Koblenzer', brewery: 'Koblenzer', country: 'Germany', continent: 'Europe', image: 'img/Germany/32.png'},
    {name: 'Einbecker Pilsener', brewery: 'Einbecker', country: 'Germany', continent: 'Europe', image: 'img/Germany/33.png'},
    {name: 'Berg', brewery: 'Berg', country: 'Germany', continent: 'Europe', image: 'img/Germany/Others/Berg.png'},
    {name: 'Härle Export Gold', brewery: 'Härle', country: 'Germany', continent: 'Europe', image: 'img/Germany/Others/Harle_Export_Gold.png'},
    {name: 'Härle Weisse', brewery: 'Härle', country: 'Germany', continent: 'Europe', image: 'img/Germany/36.png'},
    {name: 'Krombacher Weizen', brewery: 'Krombacher', country: 'Germany', continent: 'Europe', image: 'img/Germany/37.png'},
    {name: 'Bitburger Premium Pils', brewery: 'Bitburger', country: 'Germany', continent: 'Europe', image: 'img/Germany/Bitburger/Bitburger_Premium_Pils.png'},
    {name: 'Bitburger Fan Force One', brewery: 'Bitburger', country: 'Germany', continent: 'Europe', image: 'img/Germany/Bitburger/Bitburger_Fan_Force_One.png'},
    {name: 'Bitburger Alkoholfrei Radler', brewery: 'Bitburger', country: 'Germany', continent: 'Europe', image: 'img/Germany/Bitburger/Bitburger_Alkoholfrei_Radler.png'},
    {name: 'Bitburger Alkoholfrei Pils', brewery: 'Bitburger', country: 'Germany', continent: 'Europe', image: 'img/Germany/Bitburger/Bitburger_Alkoholfrei_Pils.png'},
    {name: 'BRLO Berliner Weisse', brewery: 'BRLO', country: 'Germany', continent: 'Europe', image: 'img/Germany/42.png'},
    {name: 'Ratsherrn Just craft real taste', brewery: 'Ratsherrn', country: 'Germany', continent: 'Europe', image: 'img/Germany/43.png'},
    {name: 'Gruthaus', brewery: 'Gruthaus', country: 'Germany', continent: 'Europe', image: 'img/Germany/44.png'},
    {name: 'Kehrwieder Prototyp', brewery: 'Kehrwieder', country: 'Germany', continent: 'Europe', image: 'img/Germany/45.png'},
    {name: 'Astra Urtyp', brewery: 'Astra', country: 'Germany', continent: 'Europe', image: 'img/Germany/46.png'},
    {name: 'Herrenhäuser', brewery: 'Herrenhäuser', country: 'Germany', continent: 'Europe', image: 'img/Germany/47.png'},
    {name: 'Perlenbacher', brewery: 'Perlenbacher', country: 'Germany', continent: 'Europe', image: 'img/Germany/48.png'},
    {name: 'Riegeler', brewery: 'Riegeler', country: 'Germany', continent: 'Europe', image: 'img/Germany/49.png'},
    {name: 'Sachsengold Landbier', brewery: 'Sachsengold Landbier', country: 'Germany', continent: 'Europe', image: 'img/Germany/50.png'},
    {name: 'Gold Ochsen', brewery: 'Gold Ochsen', country: 'Germany', continent: 'Europe', image: 'img/Germany/51.png'},
    {name: 'Farny', brewery: 'Farny', country: 'Germany', continent: 'Europe', image: 'img/Germany/52.png'},
    {name: 'Zoller Hof </br> Nein! Zu Fracking', brewery: 'Zoller Hof', country: 'Germany', continent: 'Europe', image: 'img/Germany/53.png'},
    {name: 'Patronus Weissbier', brewery: 'Patronus', country: 'Germany', continent: 'Europe', image: 'img/Germany/54.png'},
];