const beerSpain = [
    {name: 'Victoria </br> Malaga', brewery: 'Victoria', country: 'Spain', continent: 'Europe', image: 'img/Spain/Victoria/Victoria_Malaga.png'},
    {name: 'Victoria </br> Malagati', brewery: 'Victoria', country: 'Spain', continent: 'Europe', image: 'img/Spain/Victoria/Victoria_Malagati.png'},
    {name: 'Victoria </br> Vendeja', brewery: 'Victoria', country: 'Spain', continent: 'Europe', image: 'img/Spain/Victoria/Victoria_Vendeja.png'},
    {name: 'Victoria </br> Marengo', brewery: 'Victoria', country: 'Spain', continent: 'Europe', image: 'img/Spain/Victoria/Victoria_Marengo.png'},
    {name: 'Victoria </br> Bocoy', brewery: 'Victoria', country: 'Spain', continent: 'Europe', image: 'img/Spain/Victoria/Victoria_Bocoy.png'},
    {name: 'Victoria </br> Pasos Largos', brewery: 'Victoria', country: 'Spain', continent: 'Europe', image: 'img/Spain/Victoria/Victoria_Pasos_Largos.png'},
    {name: 'Victoria </br> 0.0%', brewery: 'Victoria', country: 'Spain', continent: 'Europe', image: 'img/Spain/Victoria/Victoria_Malaga_0.png'},
    {name: 'Victoria </br> 10', brewery: 'Victoria', country: 'Spain', continent: 'Europe', image: 'img/Spain/Victoria/Victoria_10.png'},
    {name: 'San Miguel', brewery: 'San Miguel', country: 'Spain', continent: 'Europe', image: 'img/Spain/SanMiguel/San_Miguel_2.png'},
    {name: 'San Miguel', brewery: 'San Miguel', country: 'Spain', continent: 'Europe', image: 'img/Spain/SanMiguel/San_Miguel.png'},
    {name: 'San Miguel 0.0', brewery: 'San Miguel', country: 'Spain', continent: 'Europe', image: 'img/Spain/1.png'},
    {
        name: 'San Miguel </br> Fresca',
        brewery: 'San Miguel',
        country: 'Spain',
        continent: 'Europe',
        image: 'img/Spain/SanMiguel/San_Miguel_Fresca.png'
    },
    {
        name: 'San Miguel </br> Gluten Free',
        brewery: 'San Miguel',
        country: 'Spain',
        continent: 'Europe',
        image: 'img/Spain/SanMiguel/San_Muguel_Gluten_Free.png'
    },
    {name: 'Cruzcampo </br> Pilsen', brewery: 'Cruzcampo', country: 'Spain', continent: 'Europe', image: 'img/Spain/Cruzcampo/Cruzcampo_Pilsen.png'},
    {
        name: 'Cruzcampo </br> Especial',
        brewery: 'Cruzcampo',
        country: 'Spain',
        continent: 'Europe',
        image: 'img/Spain/Cruzcampo/Cruzcampo_Especial.png'
    },
    {
        name: 'Cruzcampo </br> Especial',
        brewery: 'Cruzcampo',
        country: 'Spain',
        continent: 'Europe',
        image: 'img/Spain/Cruzcampo/Cruzcampo_Especial_2.png'
    },
    {
        name: 'Cruzcampo </br> Sin Gluten',
        brewery: 'Cruzcampo',
        country: 'Spain',
        continent: 'Europe',
        image: 'img/Spain/Cruzcampo/Cruzcampo_Sin_Gluten.png'
    },
    {
        name: 'Cruzcampo </br> Pilsen',
        brewery: 'Cruzcampo',
        country: 'Spain',
        continent: 'Europe',
        image: 'img/Spain/Cruzcampo/Cruzcampo_Pilsen_2.png'
    },
    {name: 'Ambar </br> Radler', brewery: 'Ambar', country: 'Spain', continent: 'Europe', image: 'img/Spain/Ambar/Ambar_Radler.png'},
    {name: 'Ambar </br> Morena', brewery: 'Ambar', country: 'Spain', continent: 'Europe', image: 'img/Spain/Ambar/Ambar_Morena.png'},
    {name: 'Ambar </br> IPA', brewery: 'Ambar', country: 'Spain', continent: 'Europe', image: 'img/Spain/Ambar/Ambar_IPA.png'},
    {name: 'Ramblers </br> Reserva Artesana', brewery: 'Ramblers', country: 'Spain', continent: 'Europe', image: 'img/Spain/Ramblers/Ramblers_1.png'},
    {name: 'Ramblers </br> Muy Suave', brewery: 'Ramblers', country: 'Spain', continent: 'Europe', image: 'img/Spain/Ramblers/Ramblers_2.png'},
    {name: 'Alhambra </br> Reserva 1925', brewery: 'Alhambra', country: 'Spain', continent: 'Europe', image: 'img/Spain/Alhambra/Alhambra_Reserva_1925.png'},
    {
        name: 'Alhambra </br> Reserva 1925',
        brewery: 'Alhambra',
        country: 'Spain',
        continent: 'Europe',
        image: 'img/Spain/Alhambra/Alhambra_Reserva_Barcode.png'
    },
    {
        name: 'Alhambra </br> Citra IPA',
        brewery: 'Alhambra',
        country: 'Spain',
        continent: 'Europe',
        image: 'img/Spain/Alhambra/Alhambra_Citra_IPA.png'
    },
    {
        name: 'Alhambra </br> Barrica de Ron',
        brewery: 'Alhambra',
        country: 'Spain',
        continent: 'Europe',
        image: 'img/Spain/Alhambra/Alhambra_Barrica_de_Ron.png'
    },
    {
        name: 'Alhambra </br> Reserva Roja',
        brewery: 'Alhambra',
        country: 'Spain',
        continent: 'Europe',
        image: 'img/Spain/Alhambra/Alhambra_Reserva_Roja.png'
    },
    {name: 'Estrella Galicia', brewery: 'Estrella Galicia', country: 'Spain', continent: 'Europe', image: 'img/Spain/EstrellaGalicia/Estrella_Galicia.png'},
    {name: 'Estrella Galicia </br> 0,0', brewery: 'Estrella Galicia', country: 'Spain', continent: 'Europe', image: 'img/Spain/EstrellaGalicia/Estrella_Galicia_0.png'},
    {
        name: 'Estrella Galicia </br> Primera Generacion',
        brewery: 'Estrella Galicia',
        country: 'Spain',
        continent: 'Europe',
        image: 'img/Spain/201.png'
    },
    {name: '1906 </br> La Milnueve', brewery: 'Estrella Galicia', country: 'Spain', continent: 'Europe', image: 'img/Spain/EstrellaGalicia/1906_La_Milnueve.png'},
    {name: '1906 </br> Red Vintage', brewery: 'Estrella Galicia', country: 'Spain', continent: 'Europe', image: 'img/Spain/EstrellaGalicia/1906_Red_Vintage.png'},
    {name: '1906 </br> La Pelirroja', brewery: 'Estrella Galicia', country: 'Spain', continent: 'Europe', image: 'img/Spain/EstrellaGalicia/1906_La_Pelirroja.png'},
    {name: 'El Alcazar', brewery: 'El Alcazar', country: 'Spain', continent: 'Europe', image: 'img/Spain/ElAlcazar/El_Alcazar.png'},
    {name: 'La Sagra', brewery: 'La Sagra', country: 'Spain', continent: 'Europe', image: 'img/Spain/LaSagra/La_Sagra.png'},
    {name: 'IPA Artesana', brewery: 'La Sagra', country: 'Spain', continent: 'Europe', image: 'img/Spain/64.png'},
    {name: 'Moritz', brewery: 'Cervezas Moritz', country: 'Spain', continent: 'Europe', image: 'img/Spain/Moritz/Moritz.png'},
    {
        name: 'Espiga </br> Berliner Weisse',
        brewery: 'Espiga',
        country: 'Spain',
        continent: 'Europe',
        image: 'img/Spain/Espiga/Espiga_Berliner_Weisse.png'
    },
    {name: 'Espiga </br> IPA', brewery: 'Espiga', country: 'Spain', continent: 'Europe', image: 'img/Spain/Espiga/Espiga_IPA.png'},
    {name: 'Malquerida', brewery: 'Damm', country: 'Spain', continent: 'Europe', image: 'img/Spain/Damm/Malquerida.png'},
    {name: 'Estrella Damm', brewery: 'Damm', country: 'Spain', continent: 'Europe', image: 'img/Spain/Damm/Estrella_Damm.png'},
    {name: 'Daura Damm', brewery: 'Damm', country: 'Spain', continent: 'Europe', image: 'img/Spain/Damm/Daura_Damm.png'},
    {name: 'Estrella Damm', brewery: 'Damm', country: 'Spain', continent: 'Europe', image: 'img/Spain/Damm/Estrella_Damm_2.png'},
    {name: 'Estrella Damm </br> Inedit', brewery: 'Damm', country: 'Spain', continent: 'Europe', image: 'img/Spain/Damm/Estrella_Damm_Inedit.png'},
    {name: 'Damm </br> Complot IPA', brewery: 'Damm', country: 'Spain', continent: 'Europe', image: 'img/Spain/Damm/Damm_Complot_IPA.png'},
    {name: 'Tropical </br> Pilsen', brewery: 'Tropical', country: 'Spain', continent: 'Europe', image: 'img/Spain/Tropical/Tropical_Pilsen.png'},
    {name: 'Tropical </br> Premium', brewery: 'Tropical', country: 'Spain', continent: 'Europe', image: 'img/Spain/Tropical/Tropical_Premium.png'},
    {name: 'Tropical </br> Bandido', brewery: 'Tropical', country: 'Spain', continent: 'Europe', image: 'img/Spain/Tropical/Tropical_Bandido.png'},
    {name: 'Tropical </br> Limon', brewery: 'Tropical', country: 'Spain', continent: 'Europe', image: 'img/Spain/Tropical/Tropical_Limon.png'},
    {name: 'Tropical </br> Limon', brewery: 'Tropical', country: 'Spain', continent: 'Europe', image: 'img/Spain/Tropical/Tropical_Limon_2.png'},
    {name: 'Tropical </br> Pilsen', brewery: 'Tropical', country: 'Spain', continent: 'Europe', image: 'img/Spain/Tropical/Tropical_Pilsen_2.png'},
    {name: 'Tropical </br> 1924', brewery: 'Tropical', country: 'Spain', continent: 'Europe', image: 'img/Spain/Tropical/Tropical_1924.png'},
    {
        name: 'Dorada </br> Especial Selécion de Trigo',
        brewery: 'Dorada',
        country: 'Spain',
        continent: 'Europe',
        image: 'img/Spain/Dorada/Dorada_Especial_Selecion_de_Trigo.png'
    },
    {
        name: 'Dorada </br> Especial Extra Maduracion',
        brewery: 'Dorada',
        country: 'Spain',
        continent: 'Europe',
        image: 'img/Spain/Dorada/Dorada_Especial_Extra_Maduracion.png'
    },
    {
        name: 'Dorada </br> Especial la Original',
        brewery: 'Dorada',
        country: 'Spain',
        continent: 'Europe',
        image: 'img/Spain/Dorada/Dorada_Especial_la_Original.png'
    },
    {name: 'Dorada </br> Pilsen', brewery: 'Dorada', country: 'Spain', continent: 'Europe', image: 'img/Spain/Dorada/Dorada_Pilsen.png'},
    {name: 'Dorada </br> Sin', brewery: 'Dorada', country: 'Spain', continent: 'Europe', image: 'img/Spain/Dorada/Dorada_Sin.png'},
    {name: 'Dorada </br> Sin Gluten', brewery: 'Dorada', country: 'Spain', continent: 'Europe', image: 'img/Spain/Dorada/Dorada_Sin_Gluten.png'},
    {name: 'Mahou </br> Cinco Estrellas', brewery: 'Mahou', country: 'Spain', continent: 'Europe', image: 'img/Spain/Mahou/Mahou_Cinco_Estrellas.png'},
    {name: 'Mahou </br> Cinco Estrellas Sin Gluten', brewery: 'Mahou', country: 'Spain', continent: 'Europe', image: 'img/Spain/2.png'},
    {name: 'Mahou </br> Maestra Dunkel', brewery: 'Mahou', country: 'Spain', continent: 'Europe', image: 'img/Spain/Mahou/Mahou_Maestra_Dunkel.png'},
    {name: 'Mahou </br> Maestra Doble Lupulo', brewery: 'Mahou', country: 'Spain', continent: 'Europe', image: 'img/Spain/Mahou/Mahou_Maestra_Doble_Lupulo.png'},
    {name: 'Mahou </br> Barrica Original', brewery: 'Mahou', country: 'Spain', continent: 'Europe', image: 'img/Spain/Mahou/Mahou_Barrica_Original.png'},
    {name: 'Mahou </br> Bourbon', brewery: 'Mahou', country: 'Spain', continent: 'Europe', image: 'img/Spain/Mahou/Mahou_Bourbon.png'},
    {name: 'Mahou </br> Reserva', brewery: 'Mahou', country: 'Spain', continent: 'Europe', image: 'img/Spain/Mahou/Mahou_reserva.png'},
    {name: 'Mahou </br> 0,0 Tostada', brewery: 'Mahou', country: 'Spain', continent: 'Europe', image: 'img/Spain/Mahou/Mahou_0_Tostada.png'},
    {name: 'Mahou </br> 0,0 Tostada', brewery: 'Mahou', country: 'Spain', continent: 'Europe', image: 'img/Spain//3.png'},
    {name: 'La Lager Brutus', brewery: 'Mahou', country: 'Spain', continent: 'Europe', image: 'img/Spain/205.png'},
    {name: '18/70', brewery: 'LaRubia', country: 'Spain', continent: 'Europe', image: 'img/Spain/LaRubia/1870.png'},
    {
        name: 'Legado </br> De Yuste',
        brewery: 'Legado De Yuste',
        country: 'Spain',
        continent: 'Europe',
        image: 'img/Spain/LegadoDeYuste/Legado_De_Yuste.png'
    },
    {name: 'Amstel </br> Oro', brewery: 'Amstel Cerveza', country: 'Spain', continent: 'Europe', image: 'img/Spain/Amstel/Amstel_Oro.png'},
    {name: 'El Aguila', brewery: 'El Aguila', country: 'Spain', continent: 'Europe', image: 'img/Spain/ElAguila/El_Aguila.png'},
    {name: 'El Aguila 0.0', brewery: 'El Aguila', country: 'Spain', continent: 'Europe', image: 'img/Spain/ElAguila/El_Aguila_0.png'},
    {name: 'Califa', brewery: 'Califa Cordoba', country: 'Spain', continent: 'Europe', image: 'img/Spain/Califa/Califa.png'},
    {name: 'Maternus </br> Pilsen', brewery: 'Cerveza Mica', country: 'Spain', continent: 'Europe', image: 'img/Spain/Mica/Maternus_Pilsen.png'},
    {name: 'Maternus </br> Turbia', brewery: 'Cerveza Mica', country: 'Spain', continent: 'Europe', image: 'img/Spain/Mica/Maternus_Turbia.png'},
    {name: 'Camaro Cerveza Extra', brewery: 'Camaro', country: 'Spain', continent: 'Europe', image: 'img/Spain/Camaro/Camaro.png'},
    {name: 'El Leon', brewery: 'El Leon', country: 'Spain', continent: 'Europe', image: 'img/Spain/ElLeon/El_Leon.png'},
];
