const beerSpain = [
    {name: 'Victoria </br> Malaga', brewery: 'Victoria', country: 'Spain', continent: 'Europe', image: 'img/Spain/1.png'},
    {name: 'Victoria </br> Malagati', brewery: 'Victoria', country: 'Spain', continent: 'Europe', image: 'img/Spain/2.png'},
    {name: 'Victoria </br> Vendeja', brewery: 'Victoria', country: 'Spain', continent: 'Europe', image: 'img/Spain/3.png'},
    {name: 'Victoria </br> Marengo', brewery: 'Victoria', country: 'Spain', continent: 'Europe', image: 'img/Spain/4.png'},
    {name: 'Victoria </br> Bocoy', brewery: 'Victoria', country: 'Spain', continent: 'Europe', image: 'img/Spain/5.png'},
    {name: 'Victoria </br> Pasos largos', brewery: 'Victoria', country: 'Spain', continent: 'Europe', image: 'img/Spain/6.png'},
    {name: 'Victoria </br> 0.0%', brewery: 'Victoria', country: 'Spain', continent: 'Europe', image: 'img/Spain/Victoria/Victoria_Malaga_0.png'},
    {name: 'Victoria </br> 10', brewery: 'Victoria', country: 'Spain', continent: 'Europe', image: 'img/Spain/Victoria/Victoria_10.png'},
    {name: 'San Miguel', brewery: 'San Miguel', country: 'Spain', continent: 'Europe', image: 'img/Spain/7.png'},
    {name: 'San Miguel', brewery: 'San Miguel', country: 'Spain', continent: 'Europe', image: 'img/Spain/SanMiguel/San_Miguel.png'},
    {name: 'San Miguel </br> Fresca', brewery: 'San Miguel', country: 'Spain', continent: 'Europe', image: 'img/Spain/8.png'},
    {name: 'San Miguel </br> Gluten Free', brewery: 'San Miguel', country: 'Spain', continent: 'Europe', image: 'img/Spain/SanMiguel/San_Muguel_Gluten_Free.png'},
    {name: 'Cruzcampo </br> Pilsen', brewery: 'Cruzcampo', country: 'Spain', continent: 'Europe', image: 'img/Spain/9.png'},
    {name: 'Cruzcampo </br> Especial', brewery: 'Cruzcampo', country: 'Spain', continent: 'Europe', image: 'img/Spain/10.png'},
    {name: 'Cruzcampo </br> Especial', brewery: 'Cruzcampo', country: 'Spain', continent: 'Europe', image: 'img/Spain/11.png'},
    {name: 'Cruzcampo </br> Sin Gluten', brewery: 'Cruzcampo', country: 'Spain', continent: 'Europe', image: 'img/Spain/12.png'},
    {name: 'Cruzcampo </br> Pilsen', brewery: 'Cruzcampo', country: 'Spain', continent: 'Europe', image: 'img/Spain/13.png'},
    {name: 'Ambar </br> ???', brewery: 'Ambar', country: 'Spain', continent: 'Europe', image: 'img/Spain/14.png'},
    {name: 'Ambar </br> Radler', brewery: 'Ambar', country: 'Spain', continent: 'Europe', image: 'img/Spain/15.png'},
    {name: 'Ambar </br> Morena', brewery: 'Ambar', country: 'Spain', continent: 'Europe', image: 'img/Spain/16.png'},
    {name: 'Ambar </br> IPA', brewery: 'Ambar', country: 'Spain', continent: 'Europe', image: 'img/Spain/203.png'},
    {name: 'Ramblers </br> ???', brewery: 'Ramblers', country: 'Spain', continent: 'Europe', image: 'img/Spain/17.png'},
    {name: 'Ramblers </br> ???', brewery: 'Ramblers', country: 'Spain', continent: 'Europe', image: 'img/Spain/18.png'},
    {name: 'Alhambra </br> Reserva 1925', brewery: 'Alhambra', country: 'Spain', continent: 'Europe', image: 'img/Spain/19.png'},
    {name: 'Alhambra </br> Reserva 1925', brewery: 'Alhambra', country: 'Spain', continent: 'Europe', image: 'img/Spain/Alhambra/Alhambra_Reserva_Barcode.png'},
    {name: 'Alhambra </br> Citra IPA', brewery: 'Alhambra', country: 'Spain', continent: 'Europe', image: 'img/Spain/20.png'},
    {name: 'Alhambra </br> Barrica de Ron', brewery: 'Alhambra', country: 'Spain', continent: 'Europe', image: 'img/Spain/21.png'},
    {name: 'Alhambra </br> Reserva Roja', brewery: 'Alhambra', country: 'Spain', continent: 'Europe', image: 'img/Spain/22.png'},
    {name: 'Estrella Galicia', brewery: 'Estrella Galicia', country: 'Spain', continent: 'Europe', image: 'img/Spain/23.png'},
    {name: 'Estrella Galicia </br> 0,0', brewery: 'Estrella Galicia', country: 'Spain', continent: 'Europe', image: 'img/Spain/24.png'},
    {
        name: 'Estrella Galicia </br> Primera Generacion',
        brewery: 'Estrella Galicia',
        country: 'Spain',
        continent: 'Europe',
        image: 'img/Spain/201.png'
    },
    {name: '1906 </br> La Milnueve', brewery: 'Estrella Galicia', country: 'Spain', continent: 'Europe', image: 'img/Spain/25.png'},
    {name: '1906 </br> Red Vintage', brewery: 'Estrella Galicia', country: 'Spain', continent: 'Europe', image: 'img/Spain/26.png'},
    {name: '1906 </br> La Pelirroja', brewery: 'Estrella Galicia', country: 'Spain', continent: 'Europe', image: 'img/Spain/27.png'},
    {name: 'El Alcazar', brewery: 'El Alcazar', country: 'Spain', continent: 'Europe', image: 'img/Spain/28.png'},
    {name: 'La Sagra', brewery: 'La Sagra', country: 'Spain', continent: 'Europe', image: 'img/Spain/29.png'},
    {name: 'IPA Artesana', brewery: 'La Sagra', country: 'Spain', continent: 'Europe', image: 'img/Spain/64.png'},
    {name: 'Moritz', brewery: 'Cervezas Moritz', country: 'Spain', continent: 'Europe', image: 'img/Spain/30.png'},
    {
        name: 'Espiga </br> Berliner Weisse',
        brewery: 'Companyia Artesana Maians',
        country: 'Spain',
        continent: 'Europe',
        image: 'img/Spain/31.png'
    },
    {name: 'Espiga </br> IPA', brewery: 'Companyia Artesana Maians', country: 'Spain', continent: 'Europe', image: 'img/Spain/32.png'},
    {name: 'Malquerida', brewery: 'Damm', country: 'Spain', continent: 'Europe', image: 'img/Spain/33.png'},
    {name: 'Estrella Damm', brewery: 'Damm', country: 'Spain', continent: 'Europe', image: 'img/Spain/34.png'},
    {name: 'Daura Damm', brewery: 'Damm', country: 'Spain', continent: 'Europe', image: 'img/Spain/35.png'},
    {name: 'Estrella Damm', brewery: 'Damm', country: 'Spain', continent: 'Europe', image: 'img/Spain/36.png'},
    {name: 'Estrella Damm </br> Inedit', brewery: 'Damm', country: 'Spain', continent: 'Europe', image: 'img/Spain/202.png'},
    {name: 'Damm </br> Complot IPA', brewery: 'Damm', country: 'Spain', continent: 'Europe', image: 'img/Spain/37.png'},
    {name: 'Tropical </br> Pilsen', brewery: 'Tropical', country: 'Spain', continent: 'Europe', image: 'img/Spain/38.png'},
    {name: 'Tropical </br> Premium', brewery: 'Tropical', country: 'Spain', continent: 'Europe', image: 'img/Spain/39.png'},
    {name: 'Tropical </br> ???', brewery: 'Tropical', country: 'Spain', continent: 'Europe', image: 'img/Spain/40.png'},
    {name: 'Tropical </br> Limon', brewery: 'Tropical', country: 'Spain', continent: 'Europe', image: 'img/Spain/41.png'},
    {name: 'Tropical </br> Limon', brewery: 'Tropical', country: 'Spain', continent: 'Europe', image: 'img/Spain/42.png'},
    {name: 'Tropical </br> Pilsen', brewery: 'Tropical', country: 'Spain', continent: 'Europe', image: 'img/Spain/43.png'},
    {name: 'Tropical </br> 1924', brewery: 'Tropical', country: 'Spain', continent: 'Europe', image: 'img/Spain/44.png'},
    {name: 'Dorada </br> Especial Selécion de Trigo', brewery: 'Dorada', country: 'Spain', continent: 'Europe', image: 'img/Spain/45.png'},
    {name: 'Dorada </br> Especial Extra Maduracion', brewery: 'Dorada', country: 'Spain', continent: 'Europe', image: 'img/Spain/46.png'},
    {name: 'Dorada </br> Especial la Original', brewery: 'Dorada', country: 'Spain', continent: 'Europe', image: 'img/Spain/47.png'},
    {name: 'Dorada </br> Pilsen', brewery: 'Dorada', country: 'Spain', continent: 'Europe', image: 'img/Spain/48.png'},
    {name: 'Dorada </br> Sin', brewery: 'Dorada', country: 'Spain', continent: 'Europe', image: 'img/Spain/Dorada/Dorada_Sin.png'},
    {name: 'Dorada </br> Sin Gluten', brewery: 'Dorada', country: 'Spain', continent: 'Europe', image: 'img/Spain/50.png'},
    {name: 'Mahou </br> Cinco Estrellas', brewery: 'Mahou', country: 'Spain', continent: 'Europe', image: 'img/Spain/51.png'},
    {name: 'Mahou </br> Maestra Dunkel', brewery: 'Mahou', country: 'Spain', continent: 'Europe', image: 'img/Spain/52.png'},
    {name: 'Mahou </br> Maestra Doble Lupulo', brewery: 'Mahou', country: 'Spain', continent: 'Europe', image: 'img/Spain/53.png'},
    {name: 'Mahou </br> Barrica Original', brewery: 'Mahou', country: 'Spain', continent: 'Europe', image: 'img/Spain/54.png'},
    {name: 'Mahou </br> Bourbon', brewery: 'Mahou', country: 'Spain', continent: 'Europe', image: 'img/Spain/55.png'},
    {name: 'Mahou </br> Reserva', brewery: 'Mahou', country: 'Spain', continent: 'Europe', image: 'img/Spain/Mahou/Mahou_reserva.png'},
    {name: 'Mahou </br> 0,0 Tostada', brewery: 'Mahou', country: 'Spain', continent: 'Europe', image: 'img/Spain/56.png'},
    {name: 'La Lager Brutus', brewery: 'Mahou', country: 'Spain', continent: 'Europe', image: 'img/Spain/205.png'},
    {name: '18/70', brewery: 'LaRubia', country: 'Spain', continent: 'Europe', image: 'img/Spain/57.png'},
    {
        name: 'Legado </br> De Yuste',
        brewery: 'Legado De Yuste',
        country: 'Spain',
        continent: 'Europe',
        image: 'img/Spain/Legado_De_Yuste/Legado_De_Yuste.jpg'
    },
    {name: 'Amstel </br> Oro', brewery: 'Amstel Cerveza', country: 'Spain', continent: 'Europe', image: 'img/Spain/Amstel/Amstel_Oro.png'},
    {name: 'El Aguila', brewery: 'El Aguila', country: 'Spain', continent: 'Europe', image: 'img/Spain/60.png'},
    {name: 'El Aguila 0.0', brewery: 'El Aguila', country: 'Spain', continent: 'Europe', image: 'img/Spain/ElAguila/El_Aguila_0.png'},
    {name: 'Califa', brewery: 'Califa Cordoba', country: 'Spain', continent: 'Europe', image: 'img/Spain/61.png'},
    {name: 'Maternus </br> Pilsen', brewery: 'Cerveza Mica', country: 'Spain', continent: 'Europe', image: 'img/Spain/62.png'},
    {name: 'Maternus </br> Turbia', brewery: 'Cerveza Mica', country: 'Spain', continent: 'Europe', image: 'img/Spain/Mica/Maternus_Turbia.png'},
    {name: 'Camaro Cerveza Extra', brewery: 'Camaro', country: 'Spain', continent: 'Europe', image: 'img/Spain/155.png'},
    {name: 'El Leon', brewery: 'El Leon', country: 'Spain', continent: 'Europe', image: 'img/Spain/ElLeon/El_Leon.png'},
];
